# Generated by Django 5.2.3 on 2025-06-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewill', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('invite', 'Invite-Only'), ('hidden', 'Hidden')], default='public', max_length=10),
        ),
    ]
