# Generated by Django 5.2.3 on 2025-06-29 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freewill', '0005_group_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
    ]
