# Generated by Django 5.2.3 on 2025-06-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewill', '0007_group_owner_groupmember_group_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='role',
            field=models.CharField(choices=[('read', 'Read-Only'), ('comment', 'Comment'), ('admin', 'Admin'), ('owner', 'Owner')], default='read', max_length=10),
        ),
    ]
