# Generated by Django 5.2.3 on 2025-06-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewill', '0008_alter_groupmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='default_role',
            field=models.CharField(choices=[('read', 'Read-Only'), ('comment', 'Comment')], default='read', max_length=10),
        ),
    ]
