# Generated by Django 5.2.3 on 2025-06-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewill', '0009_groupmember_default_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='default_role',
        ),
        migrations.AddField(
            model_name='group',
            name='default_role',
            field=models.CharField(choices=[('read', 'Read-Only'), ('comment', 'Comment')], default='read', max_length=10),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
