# Generated by Django 5.2.3 on 2025-06-29 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewill', '0010_remove_groupmember_default_role_group_default_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='banned_users',
            field=models.ManyToManyField(blank=True, related_name='banned_from_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
