# Generated by Django 5.2.3 on 2025-06-29 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewill', '0011_group_banned_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Group Created'), ('updated', 'Group Updated'), ('invited', 'User Invited'), ('invite_accepted', 'Invite Accepted'), ('invite_denied', 'Invite Denied'), ('join_requested', 'Join Requested'), ('join_request_deleted', 'Join Request Deleted'), ('join_request_handled', 'Join Request Handled'), ('joined', 'User Joined'), ('left', 'User Left'), ('role_changed', 'Role Changed'), ('kicked', 'User Kicked'), ('banned', 'User Banned'), ('unbanned', 'User Unbanned'), ('ownership_transferred', 'Ownership Transferred'), ('comment_edited', 'Comment Edited'), ('comment_deleted', 'Comment Deleted')], max_length=30)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='freewill.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
