# Generated by Django 5.1.5 on 2025-07-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewill', '0014_remove_group_invited_users_groupinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
