# Generated by Django 5.2.3 on 2025-07-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewill', '0016_alter_group_visibility_alter_grouplog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplog',
            name='event_type',
            field=models.CharField(choices=[('created', 'Group Created'), ('joined', 'User Joined'), ('left', 'User Left'), ('comment_posted', 'Comment Posted'), ('comment_edited', 'Comment Edited'), ('comment_deleted', 'Comment Deleted'), ('invited', 'User Invited'), ('invite_accepted', 'Invite Accepted'), ('invite_denied', 'Invite Denied'), ('invite_deleted', 'Invite Deleted'), ('join_requested', 'Join Requested'), ('join_request_deleted', 'Join Request Deleted'), ('join_request_accepted', 'Join Request Accepted'), ('join_request_denied', 'Join Request Denied'), ('role_changed', 'Role Changed'), ('kicked', 'User Kicked'), ('banned', 'User Banned'), ('unbanned', 'User Unbanned'), ('updated', 'Group Updated'), ('ownership_transferred', 'Ownership Transferred')], max_length=30),
        ),
    ]
