# Generated by Django 5.2.3 on 2025-07-18 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewill', '0017_alter_grouplog_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupjoinrequest',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='groupjoinrequest',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='banned',
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to='freewill.groupmember'),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_invites', to='freewill.groupmember'),
        ),
    ]
