# Generated by Django 5.2.3 on 2025-07-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewill', '0018_remove_groupjoinrequest_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to='freewill.groupmember'),
        ),
    ]
