# Generated by Django 5.2.3 on 2025-07-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewill', '0021_group_members_alter_group_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='channel',
            field=models.CharField(choices=[('communications', 'Communications'), ('announcements', 'Announcements')], default='communications', max_length=20),
        ),
    ]
